version: '3.4'

services:
  comfort_container:
    image: che_comfort_docker_compose_image:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    #保持容器运行
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]


  mysql_container:
    restart: always
    image: mysql:5.7.36
    container_name: mysql_image
    volumes:
      # - ./mysql/datadir:/var/lib/mysql
      # - ./mysql/conf/my.cnf:/etc/mysql/conf.d
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql123"
      # - "MYSQL_DATABASE=mydb"
      # - "TZ=Asia/Shanghai"
    ports:
      - 33060:3306

#   comfort_container:
#     image: che_ubuntu_images
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     tty: true
